### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by petterhs** [Robbe7730/pinetime-rs#2]
Hi!

Could you consider adding a license to your project? Would like to use your method of creating the MCUBoot image for bootloader support if its okay for you.

**Comment by Robbe7730** [comment]
Hello!

Thanks for asking, I normally license all my projects under MIT, but I seem to have forgotten this one. I have updated the repo to add it.

About the MCUBoot image, there are probably better/cleaner ways to do it, but this one works so that's why I'm sticking with it :smile: Feel free to contact me if you have any questions and (if you want to) keep me posted on what you end up using it for :blush:
